server:
  port: 9091

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog2
    username: root
    password: zoom
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: Blog-App
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#  security:
#    user:
#      name: kuldeep
#      password: kuldeep

logging:
  level:
    org:
      springframework:
        security: DEBUG


